title: Joseph Calica # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Entry-Level Engineer Seeking a Career in Robotics / Mechatronics
  <br><br>
  <a href="https://www.linkedin.com/in/joseph-calica/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
