title: Joseph Calica # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio where you can find various projects I have worked on in the past that showcase my skills and the hands-on application of my skills.
  <br><br>
  I am a recent Mechanical Engineering graduate seeking full-time Robotics and Mechatronics positions.
  <br><br>
  Feel free to contact me via e-mail or LinkedIn if you feel my experience aligns with any of your open positions!
  <br><br>
  <b>e-mail: josephcalica@gmail.com</b>
  <br><br>
  <a href="https://www.linkedin.com/in/joseph-calica/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://drive.google.com/file/d/1Tq7L06DwJ7WCb-rciL_qehC9cVuFwDsA/view?usp=sharing">View My Resume</a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
